import { Link } from 'react-router-dom';
import { useSeo, breadcrumbLd } from '../../../lib/seo';

export default function Privacy() {
  useSeo({
    title: 'Privacy Policy',
    description:
      'Toast2IT, LLC privacy policy — how Toast Notification collects, uses, and protects your information.',
    path: '/legal/privacy',
    jsonLd: breadcrumbLd([
      { name: 'Home', path: '/' },
      { name: 'Privacy Policy', path: '/legal/privacy' },
    ]),
  });

  return (
    <div className="m-security-page">
      <div className="m-security-inner">

        <header className="m-security-header">
          <p className="m-eyebrow">Legal</p>
          <h1>Privacy Policy</h1>
          <p className="m-security-lede">
            This Privacy Policy describes how Toast2IT, LLC (&ldquo;Company,&rdquo; &ldquo;we,&rdquo;
            &ldquo;us,&rdquo; or &ldquo;our&rdquo;) collects, uses, and discloses information
            when you use the Toast Notification service (&ldquo;Service&rdquo;). By accessing or
            using the Service, you agree to the practices described here.
          </p>
          <div className="m-security-meta">
            <span>Effective date: May 16, 2026</span>
            <span>Company: Toast2IT, LLC</span>
            <span>Contact: <a href="mailto:legal@toastnotification.com">legal@toastnotification.com</a></span>
          </div>
        </header>

        <section className="m-security-section" aria-labelledby="info-collect-heading">
          <h2 id="info-collect-heading">1. Information We Collect</h2>
          <p>We collect information you provide directly and information generated by your use of the Service.</p>
          <ul>
            <li>
              <strong>Account information</strong> &mdash; name, email address, phone number (for
              SMS multi-factor authentication), company name, and password credentials when you
              register or manage your account.
            </li>
            <li>
              <strong>Billing information</strong> &mdash; payment method details are processed
              by our payment processor and are not stored on our servers. We retain billing
              history, subscription tier, and invoice records.
            </li>
            <li>
              <strong>Service usage data</strong> &mdash; notification delivery records,
              template content, device registration identifiers, audit log events, asset files
              uploaded through the Service, and API key activity.
            </li>
            <li>
              <strong>Device and endpoint data</strong> &mdash; Windows device identifiers,
              heartbeat timestamps, and agent configuration data associated with endpoints
              enrolled through the Service.
            </li>
            <li>
              <strong>Log and technical data</strong> &mdash; IP addresses, browser or agent
              version, request timestamps, error codes, and HTTP headers generated by
              interactions with the Service.
            </li>
          </ul>
        </section>

        <section className="m-security-section" aria-labelledby="how-use-heading">
          <h2 id="how-use-heading">2. How We Use Information</h2>
          <p>We use collected information to:</p>
          <ul>
            <li>Provide, operate, and maintain the Service</li>
            <li>Process account registration and authenticate users</li>
            <li>Deliver Windows toast notifications to enrolled endpoints</li>
            <li>Process payments and manage subscriptions</li>
            <li>Send transactional communications (receipts, verification codes, security alerts)</li>
            <li>Enforce our Terms of Service and acceptable use policies</li>
            <li>Investigate security incidents, fraud, and abuse</li>
            <li>Improve reliability, performance, and features of the Service</li>
            <li>Comply with applicable legal obligations</li>
          </ul>
          <p>
            We do not sell your personal information to third parties. We do not use your
            notification content to train machine-learning models.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="sharing-heading">
          <h2 id="sharing-heading">3. Information Sharing</h2>
          <p>We share information only in the following circumstances:</p>
          <ul>
            <li>
              <strong>Service providers</strong> &mdash; with vendors who process data on our
              behalf (hosting, payment processing, SMS delivery, content moderation). These
              vendors are contractually required to protect your information and use it only
              for the services they provide to us.
            </li>
            <li>
              <strong>Legal requirements</strong> &mdash; when required by law, subpoena, or
              other legal process, or when we believe disclosure is necessary to protect the
              rights, property, or safety of Toast2IT, LLC, our customers, or others.
            </li>
            <li>
              <strong>Business transfers</strong> &mdash; in connection with a merger,
              acquisition, or sale of all or substantially all of our assets, provided the
              successor entity agrees to protect your information consistent with this policy.
            </li>
            <li>
              <strong>With your consent</strong> &mdash; in other circumstances when you have
              given us explicit permission.
            </li>
          </ul>
        </section>

        <section className="m-security-section" aria-labelledby="retention-heading">
          <h2 id="retention-heading">4. Data Retention</h2>
          <p>
            We retain account information and service data for as long as your account is
            active or as needed to provide the Service. Audit log records are retained for a
            minimum of 90 days. After account termination, we may retain certain records for
            a reasonable period as required for legal compliance, dispute resolution, and
            enforcement of our agreements. Upon verified deletion request, we will delete or
            anonymize personal data within 30 days, subject to legal retention obligations.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="security-heading">
          <h2 id="security-heading">5. Security</h2>
          <p>
            We implement administrative, technical, and physical safeguards designed to protect
            your information. These include HTTPS transport encryption, HMAC-SHA256 payload
            signing, tenant isolation, multi-factor authentication controls, and audit logging.
            No security measure is perfect. For a detailed description of our controls, see
            our <Link to="/security">Security architecture</Link> page.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="rights-heading">
          <h2 id="rights-heading">6. Your Rights and Choices</h2>
          <p>
            Depending on your location, you may have the right to access, correct, delete, or
            restrict processing of your personal information. You may also have the right to
            data portability and to withdraw consent where processing is based on consent.
          </p>
          <p>
            To exercise any of these rights, contact us at{' '}
            <a href="mailto:legal@toastnotification.com">legal@toastnotification.com</a>. We
            will respond within 30 days. We may need to verify your identity before processing
            your request.
          </p>
          <p>
            You can update account information from within the Service dashboard. You can
            request account deletion by contacting us directly.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="cookies-heading">
          <h2 id="cookies-heading">7. Cookies and Tracking</h2>
          <p>
            The Service uses session cookies and local storage for authentication state and
            user preferences. We do not use third-party advertising trackers or cross-site
            behavioral tracking technologies. Our marketing site may use basic analytics to
            understand aggregate traffic patterns. These analytics do not track individual
            users across sites.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="transfers-heading">
          <h2 id="transfers-heading">8. International Data Transfers</h2>
          <p>
            Toast2IT, LLC operates in the United States. If you access the Service from
            outside the United States, your information may be transferred to and processed
            in the United States, where data protection laws may differ from those in your
            country. By using the Service, you consent to this transfer.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="children-heading">
          <h2 id="children-heading">9. Children&rsquo;s Privacy</h2>
          <p>
            The Service is not directed to individuals under the age of 16. We do not
            knowingly collect personal information from children. If you believe a child has
            provided personal information to us, please contact us and we will delete it.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="changes-heading">
          <h2 id="changes-heading">10. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. When we make material
            changes, we will notify you by email (at the address associated with your account)
            and update the effective date above. Continued use of the Service after the
            effective date of any revised policy constitutes your acceptance of the changes.
          </p>
        </section>

        <section className="m-security-section" aria-labelledby="contact-heading">
          <h2 id="contact-heading">11. Contact Us</h2>
          <p>
            If you have questions or concerns about this Privacy Policy or our data practices,
            please contact:
          </p>
          <p>
            Toast2IT, LLC<br />
            <a href="mailto:legal@toastnotification.com">legal@toastnotification.com</a>
          </p>
        </section>

        <div className="m-security-footer-nav">
          <Link to="/" className="m-btn m-btn-ghost" style={{ fontSize: 14 }}>
            &larr; Back to home
          </Link>
          <Link to="/legal/terms" className="m-btn m-btn-ghost" style={{ fontSize: 14 }}>
            Terms of Service
          </Link>
          <a href="mailto:legal@toastnotification.com" className="m-btn m-btn-ghost" style={{ fontSize: 14 }}>
            legal@toastnotification.com
          </a>
        </div>

      </div>
    </div>
  );
}
